CREATE TABLE consultas(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    MEDICO_ID BIGINT NOT NULL,
    PACIENTE_ID BIGINT NOT NULL,
    FECHA DATETIME NOT NULL,

    PRIMARY KEY (ID),
    CONSTRAINT fk_consultas_medico_id FOREIGN KEY (MEDICO_ID) REFERENCES medicos(ID),
    CONSTRAINT fk_consultas_paciente_id FOREIGN KEY (PACIENTE_ID) REFERENCES pacientes(ID)
)